name: 'dart_tracer'
version: 0.7.0
description: A minimal path tracer.
author: Stephan Schröder <simon.void+github@gmail.com>
homepage: https://se.linkedin.com/in/stephan-schr%C3%B6der-5222aa56

environment:
  sdk: '>=2.5.0 <2.6.0'

dependencies:
  file: '5.0.10'
  stack_trace: '>=1.9.3 <1.10.0'

dev_dependencies:
  test: '>=1.8.0 <1.9.0'
