name: 'dart_tracer'
version: 0.5.1
description: A minimal path tracer.
author: Stephan Schröder <simon.void+github@gmail.com>
homepage: https://se.linkedin.com/in/stephan-schr%C3%B6der-5222aa56

environment:
  sdk: '>=1.18.1 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  file: '0.1.0'
  stack_trace: '>=1.6.6 <1.7.0'

dev_dependencies:
  test: '>=0.12.0 <1.0.0'

transformers:
- dart_to_js_script_rewriter
